import type { ReaderTranslation } from "./readerClient.js";

type AudioCallbacks = {
  onEnd: () => void;
  onError: () => void;
};

type AudioPort = {
  currentTime: number;
  playbackRate: number;
  paused: boolean;
  src: string;
  onended: (() => void) | null;
  onerror: (() => void) | null;
  play: () => Promise<void>;
  pause: () => void;
};

const configuredApiBase: unknown = import.meta.env["VITE_API_BASE_URL"];
const API_BASE_URL =
  typeof configuredApiBase === "string" && configuredApiBase !== ""
    ? configuredApiBase
    : "http://localhost:8000";

/**
 * Plays an editorial audio asset generated by a backend provider such as OpenAI.
 *
 * The API key is never present here: the browser receives only the published MP3 URL.
 */
export class PublishedAudioNarrator {
  private loadedUri: string | null = null;
  private resumeReady = false;

  constructor(private readonly audio: AudioPort | null) {}

  canNarrate(translation: ReaderTranslation): boolean {
    return this.audio !== null && !translation.audio.simulated && translation.audio.uri !== "";
  }

  get currentTimeMs(): number {
    return Math.max(0, Math.round((this.audio?.currentTime ?? 0) * 1000));
  }

  start(
    translation: ReaderTranslation,
    startTimeMs: number,
    rate: number,
    callbacks: AudioCallbacks,
  ): boolean {
    if (!this.canNarrate(translation) || this.audio === null) {
      return false;
    }
    const uri = resolvePublishedAudioUrl(translation.audio.uri);
    if (this.loadedUri !== uri) {
      this.audio.src = uri;
      this.loadedUri = uri;
    }
    this.audio.currentTime = Math.max(0, startTimeMs) / 1000;
    this.audio.playbackRate = rate;
    this.audio.onended = callbacks.onEnd;
    this.audio.onerror = callbacks.onError;
    this.resumeReady = true;
    void this.audio.play().catch(callbacks.onError);
    return true;
  }

  pause(): void {
    if (this.loadedUri !== null) {
      this.audio?.pause();
    }
  }

  resume(): boolean {
    if (this.audio === null || this.loadedUri === null || !this.resumeReady || !this.audio.paused) {
      return false;
    }
    void this.audio.play();
    return true;
  }

  stop(): void {
    if (this.loadedUri !== null) {
      this.audio?.pause();
    }
    this.resumeReady = false;
  }
}

export const resolvePublishedAudioUrl = (uri: string): string => {
  if (/^https?:\/\//u.test(uri)) {
    return uri;
  }
  return new URL(uri, `${API_BASE_URL}/`).toString();
};

export const createPublishedAudioNarrator = (): PublishedAudioNarrator => {
  const audio = document.createElement("audio") as unknown as AudioPort;
  return new PublishedAudioNarrator(audio);
};
