"""create functional data model

Revision ID: 2bf6cf5e1177
Revises: 20260724_0001
Create Date: 2026-07-24 11:18:10.528736
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2bf6cf5e1177"
down_revision: str | None = "20260724_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "reading_levels",
        sa.Column(
            "code",
            sa.Enum(
                "beginner",
                "elementary",
                "intermediate",
                "upper-intermediate",
                "advanced",
                name="reading_level_code",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "display_order >= 0", name=op.f("ck_reading_levels_non_negative_display_order")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_levels")),
        sa.UniqueConstraint("code", name=op.f("uq_reading_levels_code")),
        sa.UniqueConstraint("display_order", name=op.f("uq_reading_levels_display_order")),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("external_subject", sa.String(length=200), nullable=True),
        sa.Column("email_normalized", sa.String(length=320), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_valid_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email_normalized", name=op.f("uq_users_email_normalized")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_status"), ["status"], unique=False)

    op.create_table(
        "administrators",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_administrators_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_administrators")),
        sa.UniqueConstraint("user_id", name=op.f("uq_administrators_user_id")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.String(length=160), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('succeeded', 'failed', 'denied')", name=op.f("ck_audit_logs_valid_outcome")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_logs_target_id"), ["target_id"], unique=False)

    op.create_table(
        "reading_contents",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "story",
                "article",
                "book",
                "lesson",
                name="content_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "audience",
            sa.Enum(
                "children",
                "teenager",
                "adult",
                "all",
                name="audience",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reading_level_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_level_id"],
            ["reading_levels.id"],
            name=op.f("fk_reading_contents_reading_level_id_reading_levels"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_contents")),
        sa.UniqueConstraint("slug", name=op.f("uq_reading_contents_slug")),
    )
    with op.batch_alter_table("reading_contents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reading_contents_reading_level_id"), ["reading_level_id"], unique=False
        )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "content_categories",
        sa.Column("reading_content_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_content_categories_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reading_content_id"],
            ["reading_contents.id"],
            name=op.f("fk_content_categories_reading_content_id_reading_contents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "reading_content_id", "category_id", name=op.f("pk_content_categories")
        ),
    )
    op.create_table(
        "content_versions",
        sa.Column("reading_content_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready_for_processing",
                "processing",
                "processing_failed",
                "ready_for_review",
                "review_rejected",
                "approved",
                "published",
                "unpublished",
                "archived",
                name="editorial_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=71), nullable=True),
        sa.Column("package_url", sa.String(length=500), nullable=True),
        sa.Column("minimum_app_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_content_versions_positive_version_number")
        ),
        sa.ForeignKeyConstraint(
            ["reading_content_id"],
            ["reading_contents.id"],
            name=op.f("fk_content_versions_reading_content_id_reading_contents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_versions")),
        sa.UniqueConstraint(
            "reading_content_id",
            "version_number",
            name=op.f("uq_content_versions_reading_content_id"),
        ),
    )
    with op.batch_alter_table("content_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_versions_reading_content_id"),
            ["reading_content_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_content_versions_status"), ["status"], unique=False)

    op.create_table(
        "favorites",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reading_content_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_content_id"],
            ["reading_contents.id"],
            name=op.f("fk_favorites_reading_content_id_reading_contents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorites")),
        sa.UniqueConstraint("user_id", "reading_content_id", name=op.f("uq_favorites_user_id")),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_favorites_reading_content_id"), ["reading_content_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audio_assets",
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum(
                "en", "es", name="resource_language", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("voice_id", sa.String(length=120), nullable=False),
        sa.Column("uri", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=71), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "invalid",
                "archived",
                name="resource_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_ms > 0", name=op.f("ck_audio_assets_positive_duration")),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_audio_assets_content_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_assets")),
        sa.UniqueConstraint(
            "content_version_id",
            "language",
            "voice_id",
            name=op.f("uq_audio_assets_content_version_id"),
        ),
    )
    with op.batch_alter_table("audio_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audio_assets_content_version_id"), ["content_version_id"], unique=False
        )

    op.create_table(
        "content_translations",
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("en", "es", name="language", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_content_translations_content_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_translations")),
        sa.UniqueConstraint(
            "content_version_id",
            "language",
            name=op.f("uq_content_translations_content_version_id"),
        ),
    )
    with op.batch_alter_table("content_translations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_translations_content_version_id"),
            ["content_version_id"],
            unique=False,
        )

    op.create_table(
        "download_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(length=160), nullable=False),
        sa.Column("operation_id", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "downloaded",
                "verified",
                "removed",
                "failed",
                name="download_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=71), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_download_records_content_version_id_content_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_download_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_download_records")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_download_records_operation_id")),
        sa.UniqueConstraint(
            "user_id", "content_version_id", "client_id", name=op.f("uq_download_records_user_id")
        ),
    )
    with op.batch_alter_table("download_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_download_records_content_version_id"),
            ["content_version_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_download_records_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_download_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "processing_jobs",
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum(
                "en", "es", name="resource_language", native_enum=False, create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=80), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "estimated_cost >= 0", name=op.f("ck_processing_jobs_non_negative_cost")
        ),
        sa.CheckConstraint(
            "progress_percent <= 100", name=op.f("ck_processing_jobs_bounded_progress")
        ),
        sa.CheckConstraint(
            "progress_percent >= 0", name=op.f("ck_processing_jobs_non_negative_progress")
        ),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_processing_jobs_content_version_id_content_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_processing_jobs_idempotency_key")),
    )
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_processing_jobs_content_version_id"),
            ["content_version_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_processing_jobs_status"), ["status"], unique=False)

    op.create_table(
        "publications",
        sa.Column("reading_content_id", sa.Uuid(), nullable=False),
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("unpublished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_publications_content_version_id_content_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reading_content_id"],
            ["reading_contents.id"],
            name=op.f("fk_publications_reading_content_id_reading_contents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint("content_version_id", name=op.f("uq_publications_content_version_id")),
        sa.UniqueConstraint("reading_content_id", name=op.f("uq_publications_reading_content_id")),
    )
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_publications_is_active"), ["is_active"], unique=False)

    op.create_table(
        "reading_progress",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reading_content_id", sa.Uuid(), nullable=False),
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column("stable_anchor", sa.String(length=160), nullable=False),
        sa.Column("position_ms", sa.Integer(), nullable=False),
        sa.Column("last_operation_id", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "position_ms >= 0", name=op.f("ck_reading_progress_non_negative_position")
        ),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_reading_progress_content_version_id_content_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reading_content_id"],
            ["reading_contents.id"],
            name=op.f("fk_reading_progress_reading_content_id_reading_contents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reading_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_progress")),
        sa.UniqueConstraint(
            "last_operation_id", name=op.f("uq_reading_progress_last_operation_id")
        ),
        sa.UniqueConstraint(
            "user_id", "reading_content_id", name=op.f("uq_reading_progress_user_id")
        ),
    )
    with op.batch_alter_table("reading_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reading_progress_reading_content_id"),
            ["reading_content_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_reading_progress_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chapters",
        sa.Column("content_translation_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_chapters_non_negative_position")),
        sa.ForeignKeyConstraint(
            ["content_translation_id"],
            ["content_translations.id"],
            name=op.f("fk_chapters_content_translation_id_content_translations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapters")),
        sa.UniqueConstraint(
            "content_translation_id", "position", name=op.f("uq_chapters_content_translation_id")
        ),
        sa.UniqueConstraint(
            "content_translation_id", "stable_key", name=op.f("uq_chapters_content_translation_id")
        ),
    )
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chapters_content_translation_id"),
            ["content_translation_id"],
            unique=False,
        )

    op.create_table(
        "paragraphs",
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=120), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(text)) > 0", name=op.f("ck_paragraphs_non_empty_text")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_paragraphs_non_negative_position")),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_paragraphs_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paragraphs")),
        sa.UniqueConstraint("chapter_id", "position", name=op.f("uq_paragraphs_chapter_id")),
        sa.UniqueConstraint("chapter_id", "stable_key", name=op.f("uq_paragraphs_chapter_id")),
    )
    with op.batch_alter_table("paragraphs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_paragraphs_chapter_id"), ["chapter_id"], unique=False)

    op.create_table(
        "illustrations",
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column("paragraph_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=71), nullable=False),
        sa.Column("alt_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "invalid",
                "archived",
                name="resource_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_illustrations_non_negative_position")),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_illustrations_content_version_id_content_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paragraph_id"],
            ["paragraphs.id"],
            name=op.f("fk_illustrations_paragraph_id_paragraphs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_illustrations")),
        sa.UniqueConstraint(
            "content_version_id", "position", name=op.f("uq_illustrations_content_version_id")
        ),
    )
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_illustrations_content_version_id"), ["content_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_illustrations_paragraph_id"), ["paragraph_id"], unique=False
        )

    op.create_table(
        "speech_marks",
        sa.Column("audio_asset_id", sa.Uuid(), nullable=False),
        sa.Column("paragraph_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("mark_type", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=240), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "mark_type IN ('word', 'sentence')", name=op.f("ck_speech_marks_valid_mark_type")
        ),
        sa.CheckConstraint("char_end >= char_start", name=op.f("ck_speech_marks_valid_char_range")),
        sa.CheckConstraint("char_start >= 0", name=op.f("ck_speech_marks_non_negative_char_start")),
        sa.CheckConstraint("end_ms >= start_ms", name=op.f("ck_speech_marks_valid_time_range")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_speech_marks_non_negative_position")),
        sa.CheckConstraint("start_ms >= 0", name=op.f("ck_speech_marks_non_negative_start")),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"],
            ["audio_assets.id"],
            name=op.f("fk_speech_marks_audio_asset_id_audio_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paragraph_id"],
            ["paragraphs.id"],
            name=op.f("fk_speech_marks_paragraph_id_paragraphs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speech_marks")),
        sa.UniqueConstraint(
            "audio_asset_id", "position", name=op.f("uq_speech_marks_audio_asset_id")
        ),
    )
    with op.batch_alter_table("speech_marks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_speech_marks_audio_asset_id"), ["audio_asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_speech_marks_paragraph_id"), ["paragraph_id"], unique=False
        )

    op.create_table(
        "vocabulary_words",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content_version_id", sa.Uuid(), nullable=False),
        sa.Column("paragraph_id", sa.Uuid(), nullable=True),
        sa.Column(
            "language",
            sa.Enum(
                "en", "es", name="vocabulary_language", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("word", sa.String(length=160), nullable=False),
        sa.Column("normalized_word", sa.String(length=160), nullable=False),
        sa.Column("stable_anchor", sa.String(length=160), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_version_id"],
            ["content_versions.id"],
            name=op.f("fk_vocabulary_words_content_version_id_content_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paragraph_id"],
            ["paragraphs.id"],
            name=op.f("fk_vocabulary_words_paragraph_id_paragraphs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_vocabulary_words_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_words")),
        sa.UniqueConstraint(
            "user_id",
            "content_version_id",
            "language",
            "normalized_word",
            "stable_anchor",
            name=op.f("uq_vocabulary_words_user_id"),
        ),
    )
    with op.batch_alter_table("vocabulary_words", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vocabulary_words_content_version_id"),
            ["content_version_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_vocabulary_words_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vocabulary_words", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vocabulary_words_user_id"))
        batch_op.drop_index(batch_op.f("ix_vocabulary_words_content_version_id"))

    op.drop_table("vocabulary_words")
    with op.batch_alter_table("speech_marks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_speech_marks_paragraph_id"))
        batch_op.drop_index(batch_op.f("ix_speech_marks_audio_asset_id"))

    op.drop_table("speech_marks")
    with op.batch_alter_table("illustrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_illustrations_paragraph_id"))
        batch_op.drop_index(batch_op.f("ix_illustrations_content_version_id"))

    op.drop_table("illustrations")
    with op.batch_alter_table("paragraphs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paragraphs_chapter_id"))

    op.drop_table("paragraphs")
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chapters_content_translation_id"))

    op.drop_table("chapters")
    with op.batch_alter_table("reading_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reading_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_reading_progress_reading_content_id"))

    op.drop_table("reading_progress")
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publications_is_active"))

    op.drop_table("publications")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processing_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_processing_jobs_content_version_id"))

    op.drop_table("processing_jobs")
    with op.batch_alter_table("download_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_download_records_user_id"))
        batch_op.drop_index(batch_op.f("ix_download_records_status"))
        batch_op.drop_index(batch_op.f("ix_download_records_content_version_id"))

    op.drop_table("download_records")
    with op.batch_alter_table("content_translations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_translations_content_version_id"))

    op.drop_table("content_translations")
    with op.batch_alter_table("audio_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audio_assets_content_version_id"))

    op.drop_table("audio_assets")
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))
        batch_op.drop_index(batch_op.f("ix_favorites_reading_content_id"))

    op.drop_table("favorites")
    with op.batch_alter_table("content_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_versions_status"))
        batch_op.drop_index(batch_op.f("ix_content_versions_reading_content_id"))

    op.drop_table("content_versions")
    op.drop_table("content_categories")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    with op.batch_alter_table("reading_contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reading_contents_reading_level_id"))

    op.drop_table("reading_contents")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    op.drop_table("administrators")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_status"))

    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("reading_levels")
    op.drop_table("permissions")
    op.drop_table("categories")
    # ### end Alembic commands ###
