"""Application services and stable domain errors."""

from followread_api.services.authentication import (
    AuthenticatedUser,
    AuthenticationService,
    IssuedSession,
)
from followread_api.services.authorization import (
    PERMISSION_DESCRIPTIONS,
    ROLE_PERMISSION_MATRIX,
    ensure_rbac_matrix,
    require_permission,
)
from followread_api.services.bootstrap import (
    BootstrapConflictError,
    BootstrapInputError,
    BootstrapResult,
    bootstrap_superadmin,
)
from followread_api.services.catalog import CatalogReader, CatalogService
from followread_api.services.dashboard import DashboardService, DashboardSummary
from followread_api.services.editor import (
    EditorChapter,
    EditorDocument,
    EditorialEditorService,
    EditorParagraph,
    EditorTranslation,
)
from followread_api.services.editorial_catalog import (
    CreateEditorialContent,
    EditorialCatalogFilters,
    EditorialCatalogPage,
    EditorialCatalogService,
)
from followread_api.services.errors import (
    AuthenticationRequiredError,
    ContentNotFoundError,
    DomainError,
    EditorConflictError,
    ErrorCode,
    InvalidCatalogQueryError,
    InvalidCredentialsError,
    InvalidCsrfTokenError,
    InvalidOriginError,
    PermissionDeniedError,
)
from followread_api.services.illustrations import IllustrationResource, IllustrationService
from followread_api.services.polly import (
    COST_PER_CHARACTER,
    VOICE_LABELS,
    VOICE_LANGUAGES,
    AwsPollyAdapter,
    FakePollyAdapter,
    LocalAudioStorage,
    OpenAITtsAdapter,
    PollyAdapter,
    PollyProcessingService,
    RetryingPollyAdapter,
    TextChunker,
)
from followread_api.services.reader_package import (
    ReaderAudio,
    ReaderChapter,
    ReaderMark,
    ReaderPackage,
    ReaderPackageService,
    ReaderParagraph,
    ReaderTranslation,
)
from followread_api.services.review import (
    EditorialReviewService,
    ReviewCheck,
    ReviewEvent,
    ReviewSnapshot,
)

__all__ = [
    "COST_PER_CHARACTER",
    "PERMISSION_DESCRIPTIONS",
    "ROLE_PERMISSION_MATRIX",
    "VOICE_LABELS",
    "VOICE_LANGUAGES",
    "AuthenticatedUser",
    "AuthenticationRequiredError",
    "AuthenticationService",
    "AwsPollyAdapter",
    "BootstrapConflictError",
    "BootstrapInputError",
    "BootstrapResult",
    "CatalogReader",
    "CatalogService",
    "ContentNotFoundError",
    "CreateEditorialContent",
    "DashboardService",
    "DashboardSummary",
    "DomainError",
    "EditorChapter",
    "EditorConflictError",
    "EditorDocument",
    "EditorParagraph",
    "EditorTranslation",
    "EditorialCatalogFilters",
    "EditorialCatalogPage",
    "EditorialCatalogService",
    "EditorialEditorService",
    "EditorialReviewService",
    "ErrorCode",
    "FakePollyAdapter",
    "IllustrationResource",
    "IllustrationService",
    "InvalidCatalogQueryError",
    "InvalidCredentialsError",
    "InvalidCsrfTokenError",
    "InvalidOriginError",
    "IssuedSession",
    "LocalAudioStorage",
    "OpenAITtsAdapter",
    "PermissionDeniedError",
    "PollyAdapter",
    "PollyProcessingService",
    "ReaderAudio",
    "ReaderChapter",
    "ReaderMark",
    "ReaderPackage",
    "ReaderPackageService",
    "ReaderParagraph",
    "ReaderTranslation",
    "RetryingPollyAdapter",
    "ReviewCheck",
    "ReviewEvent",
    "ReviewSnapshot",
    "TextChunker",
    "bootstrap_superadmin",
    "ensure_rbac_matrix",
    "require_permission",
]
